### ISSUE TITLE
Roadmap to v0.1.0 release

### ISSUE THREAD

**Issue by awrznc** [awrznc/GalM#9]
## Todo List

* [x] Add GalM Command
* [x] Add Sort Example
* [x] Add function of stdi
* [x] CRLF to LF
* [x] Add following characters ( over 1000 )
* [x] Add Overview

### Out of scope

* Add Iterator for std::str::Split and std::slice::Iter ( `std::char`, `std::string::String` )

### Not-to-do List

* Update logo
* Add figure for explanation

**Comment by awrznc** [comment]
#28 #29 で対応したのでcloseします。
